server:
  port: 8080

weather:
  api:
    uri: https://api.openweathermap.org/data/2.5/weather
    key: ${API_KEY}

spring:
  application:
    name: weather-tracker
  datasource:
    url: jdbc:postgresql://localhost:5438/weather-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
