server:
  port: 8080
  servlet:
    context-path: /weather-tracker

spring:
  application:
    name: weather-tracker
  datasource:
    url: jdbc:postgresql://localhost:5438/weather-db
    username: postgres
    password: 12345
