server:
  port: 8080

weather:
  api:
    uri: https://api.openweathermap.org/data/2.5/weather
    key: a1dabe8ddd734cd61cfdd9c3b2396966

spring:
  application:
    name: weather-tracker
  datasource:
    url: jdbc:postgresql://localhost:5438/weather-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
